[package]
name = "zanop-kernel"
version = "0.0.4"
edition = "2021"
authors = ["Zanop Technologies"]
description = "The Zanop OS kernel (terminal-only)"
license-file = "LICENSE"

[[bin]]
name = "zanop-kernel"
path = "src/main.rs"

[dependencies]
spin = "0.9"
volatile = "0.4"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
bitflags = "2"

[profile.dev]
panic = "abort"   # required — no unwinding support in no_std

[profile.release]
panic = "abort"
lto = true